### ISSUE TITLE
Ari Crashes when Refreshing the Page

### ISSUE THREAD

**Issue by CaveNightingale** [Andy-K-Sparklight/ACH#36]
Step to reproduce:
1. start `Ari`
2. wait for the window
3. click refresh
4. see Segmentation fault

```
Thread 1 "Ari" received signal SIGSEGV, Segmentation fault.
0x00005555556c776c in webview::detail::gtk_webkit_engine::set_size (hints=0, height=0, width=0, this=0x20) at ../inc/webview.h:506
506         gtk_window_set_resizable(GTK_WINDOW(m_window), hints != WEBVIEW_HINT_FIXED);
(gdb) bt
#0  0x00005555556c776c in webview::detail::gtk_webkit_engine::set_size(int, int, int) (hints=0, height=0, width=0, this=0x20) at ../inc/webview.h:506
#1  webview_set_size (hints=0, height=0, width=0, w=0x20) at ../inc/webview.h:1653
#2  operator() (__closure=0x0, seq=<optimized out>, arg=0x555555a79e30, req=<optimized out>) at ../src/Main.cc:73
#3  _FUN(char const*, char const*, void*) () at ../src/Main.cc:77
#4  0x00005555556cd284 in std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*)>::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*) const (__args#2=<optimized out>, __args#1="[1946,1317,1167,790]", __args#0="1", this=0x5555558c51f0)
    at /usr/include/c++/12/bits/std_function.h:591
#5  webview::webview::on_message(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=<optimized out>, msg=<optimized out>)
    at ../inc/webview.h:1610
#6  0x00005555556cb1d8 in webview::detail::gtk_webkit_engine::gtk_webkit_engine(bool, void*)::{lambda(_WebKitUserContentManager*, _WebKitJavascriptResult*, void*)#2}::operator()(_WebKitUserContentManager*, _WebKitJavascriptResult*, void*) const (__closure=0x0, arg=0x555555788340, r=<optimized out>) at /usr/include/c++/12/bits/basic_string.tcc:238
#7  webview::detail::gtk_webkit_engine::gtk_webkit_engine(bool, void*)::{lambda(_WebKitUserContentManager*, _WebKitJavascriptResult*, void*)#2}::_FUN(_WebKitUserContentManager*, _WebKitJavascriptResult*, void*) () at ../inc/webview.h:460
#8  0x00007ffff7e7cf50 in g_closure_invoke (closure=0x555555c43670, return_value=0x0, n_param_values=2, param_values=0x7fffffffcc10, invocation_hint=0x7fffffffcb90)
    at ../../../gobject/gclosure.c:832
#9  0x00007ffff7eaad66 in signal_emit_unlocked_R.isra.0
    (node=node@entry=0x5555559585a0, detail=detail@entry=1744, instance=instance@entry=0x5555558ce420, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffcc10) at ../../../gobject/gsignal.c:3796
#10 0x00007ffff7e9b17a in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffcdd0)
    at ../../../gobject/gsignal.c:3549
#11 0x00007ffff7e9b403 in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../../../gobject/gsignal.c:3606
#12 0x00007ffff3d5b39f in ScriptMessageClientGtk::didPostMessage(WebKit::WebPageProxy&, WebKit::FrameInfoData&&, API::ContentWorld&, WebCore::SerializedScriptValue&) ()
    at ./Source/WebKit/UIProcess/API/glib/WebKitUserContentManager.cpp:239
#13 0x00007ffff3defd5b in WebKit::WebUserContentControllerProxy::didPostMessage(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long, WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::CompletionHandler<void (WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::String const&)>&&) () at ./Source/WebKit/UIProcess/UserContent/WebUserContentControllerProxy.cpp:343
#14 0x00007ffff39c858a in IPC::callMemberFunctionImpl<WebKit::WebUserContentControllerProxy, void (WebKit::WebUserContentControllerProxy::*)(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long, WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::CompletionHandler<void (WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::String const&)>&&), void (WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::String const&), std::tuple<WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData, unsigned long, WTF::Span<unsigned char const, 18446744073709551615ul> >, 0ul, 1ul, 2ul, 3ul>(WebKit::WebUserContentControllerProxy*, void (WebKit::WebUserContentControllerProxy::*)(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long, WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::CompletionHandler<void (WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::String const&)>&&), WTF::CompletionHandler<void (WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::String const&)>&&, std::tuple<WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData, unsigned long, WTF::Span<unsigned char const, 18446744073709551615ul> >&&, std::integer_sequence<unsigned long, 0ul, 1ul, 2ul, 3ul>) ()
    at ./Source/WebKit/Platform/IPC/HandleMessage.h:145
#15 IPC::callMemberFunction<WebKit::WebUserContentControllerProxy, void (WebKit::WebUserContentControllerProxy::*)(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long, WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::CompletionHandler<void (WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::String const&)>&&), void (WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::String const&), std::tuple<WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData, unsigned long, WTF::Span<unsigned char const, 18446744073709551615ul> >, std::integer_sequence<unsigned long, 0ul, 1ul, 2ul, 3ul> >(std::tuple<WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData, unsigned long, WTF::Span<unsigned char const, 18446744073709551615ul> >&&, WTF::CompletionHandler<void (WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::String const&)>&&, WebKit::WebUserContentControllerProxy*, void (WebKit::WebUserContentControllerProxy::*)(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long, WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::CompletionHandler<void (WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::String const&)>&&)) ()
    at ./Source/WebKit/Platform/IPC/HandleMessage.h:151
#16 IPC::handleMessageAsync<Messages::WebUserContentControllerProxy::DidPostMessage, WebKit::WebUserContentControllerProxy, void (WebKit::WebUserContentControllerProxy::*)(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long, WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::CompletionHandler<void (WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::String const&)>&&)>(IPC::Connection&, IPC::Decoder&, WebKit::WebUserContentControllerProxy*, void (WebKit::WebUserContentControllerProxy::*)(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long, WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::CompletionHandler<void (WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::String const&)>&&)) ()
    at ./Source/WebKit/Platform/IPC/HandleMessage.h:353
#17 0x00007ffff39c7e38 in WebKit::WebUserContentControllerProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&) ()
    at DerivedSources/WebKit/WebUserContentControllerProxyMessageReceiver.cpp:79
#18 0x00007ffff3bb5aa8 in IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&) () at ./Source/WebKit/Platform/IPC/MessageReceiverMap.cpp:129
#19 0x00007ffff3c6b4d6 in WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&) () at ./Source/WebKit/UIProcess/WebProcessProxy.cpp:832
#20 0x00007ffff3baeac5 in IPC::Connection::dispatchMessage(std::unique_ptr<IPC::Decoder, std::default_delete<IPC::Decoder> >) ()
    at ./Source/WebKit/Platform/IPC/Connection.cpp:1150
--Type <RET> for more, q to quit, c to continue without paging--
#21 0x00007ffff3bb0ddf in IPC::Connection::dispatchIncomingMessages() () at ./Source/WebKit/Platform/IPC/Connection.cpp:1254
#22 0x00007ffff2d187a5 in WTF::Function<void ()>::operator()() const () at ./Source/WTF/wtf/Function.h:82
#23 WTF::RunLoop::performWork() () at ./Source/WTF/wtf/RunLoop.cpp:133
#24 0x00007ffff2d76f0d in operator() () at ./Source/WTF/wtf/glib/RunLoopGLib.cpp:80
#25 _FUN() () at ./Source/WTF/wtf/glib/RunLoopGLib.cpp:82
#26 0x00007ffff2d777f3 in operator() () at ./Source/WTF/wtf/glib/RunLoopGLib.cpp:53
#27 _FUN() () at ./Source/WTF/wtf/glib/RunLoopGLib.cpp:56
#28 0x00007ffff791c43f in g_main_dispatch (context=0x5555557d6970) at ../../../glib/gmain.c:3444
#29 g_main_context_dispatch (context=0x5555557d6970) at ../../../glib/gmain.c:4162
#30 0x00007ffff79713c8 in g_main_context_iterate.constprop.0 (context=0x5555557d6970, block=<optimized out>, dispatch=1, self=<optimized out>) at ../../../glib/gmain.c:4238
#31 0x00007ffff791baef in g_main_loop_run (loop=0x555555bc2ec0) at ../../../glib/gmain.c:4438
#32 0x00007ffff724756d in gtk_main () at ../../../../gtk/gtkmain.c:1329
#33 0x00005555555a4c96 in webview::detail::gtk_webkit_engine::run() (this=0x555555788340) at ../inc/webview.h:490
#34 webview_run (w=0x555555788340) at ../inc/webview.h:1631
#35 main(int, char**) (argc=1, argv=<optimized out>) at ../src/Main.cc:185
```

**Comment by Andy-K-Sparklight** [comment]
This is work as designed. The page **should not** be refreshed.
In production releases debug mode will be set to false, with context menu removed also.

**Comment by CaveNightingale** [comment]
If the page is not refreshable, you should write it into the document.


Currently,you don't provide a way to exit the log displaying screen so definately people will want to refresh.



---Original---
From: "Annie K Rarity ***@***.***&gt;
Date: Mon, Jan 30, 2023 16:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Andy-K-Sparklight/Ari] Ari Crashes when Refreshing the Page(Issue #36)




 
This is work as designed. The page should not be refreshed.
 In production releases debug mode will be set to false, with context menu removed also.

**Comment by CaveNightingale** [comment]
Currently, Ari has *NO* document, unit tests or tutorial.


Participant don't know what's the expected behaviour.



---Original---
From: "Annie K Rarity ***@***.***&gt;
Date: Mon, Jan 30, 2023 16:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Andy-K-Sparklight/Ari] Ari Crashes when Refreshing the Page(Issue #36)




 
This is work as designed. The page should not be refreshed.
 In production releases debug mode will be set to false, with context menu removed also.

**Comment by Andy-K-Sparklight** [comment]
We provided no way to refresh the page in a normal way of accessing. Documentation are for normal use cases rather than development.
Any crashes caused by using development tools like debuggers or DevTools (including debugging context menu) are not supported.

**Comment by CaveNightingale** [comment]
Is refreshing really DevTools? I don't think so.


I strongly disagree with you. Documents should be a contract for developers, testers, and users. They tell developers what to implement and tell testers what is an legal input and expected behavior.


What's more, since you are exposing `tellSize` to untrustable code from internet such as Modrinth and Microsoft, this function acts as a boundary between trusted and untrustable code and should't be so vulnerable.


If this means nothing to you, I'm going to quit.

**Comment by Andy-K-Sparklight** [comment]
It's a pity to hear that.

Safety values a lot to us. However, it's impossible for our developers to add new features while writing documentation under such heavy pressure. Also, this project is still at its early stage, many things are not mature yet. So don't be too anxious.

Anyway, we respect each contributor's own choice. They might leave at anytime and are still welcomed to come back at a more completed stage.

No mean to offend, but if any, I apologize in advance.
